spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lgdms_test
    username: lgdms_test
    password: test123
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
